### ISSUE TITLE
Deletion?

### ISSUE THREAD

**Issue by ParthKolekar** [felicity-iiith/felicity-iiith.github.io#2]
@polybuildr 
@nisargjhaveri 
@hharchani 

Could we delete this? 
Not being used anywhere....

**Comment by polybuildr** [comment]
Yeah, I'm fine with deleting this.

/cc @nisargjhaveri @hharchani ?

**Comment by hharchani** [comment]
Sure.

**Comment by ParthKolekar** [comment]
2 approvals are enough. 

Down she goes.....
